# Generated by Django 4.2.12 on 2024-06-06 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="review",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="watchlist",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="watchlist_app.watchlist",
            ),
            preserve_default=False,
        ),
    ]
